declare let config: {
    VISIBLE_SETS_COUNT: number;
    KEYBOARD_REPEAT_TIMEOUT: number;
    boardWidth: number;
    boardHeight: number;
    boardPadding: number;
    ballDiameter: number;
    paddleWidth: number;
    paddleHeight: number;
    maxBounceAngle: number;
    playerSpeed: number;
    ballSpeed: number;
    ballSpeedEnvStep: number;
    ballSpeedEnvFinal: number;
    maxMutation: number;
    maxMutationEnvStep: number;
    maxMutationEnvFinal: number;
    wallMinAngle: number;
    wallMinAngleEnvStep: number;
    wallMinAngleEnvFinal: number;
    move: number;
    moveEnvStep: number;
    moveEnvFinal: number;
    bounce: number;
    bounceEnvStep: number;
    bounceEnvFinal: number;
    fail: number;
    failEnvStep: number;
    failEnvFinal: number;
    population: number;
    divisionThreshold: number;
    divisionScore: number;
    maxThreshold: number;
    maxBias: number;
    populationIncreaseMulti: number;
};
export type Config = typeof config;
export declare const getConfig: () => {
    VISIBLE_SETS_COUNT: number;
    KEYBOARD_REPEAT_TIMEOUT: number;
    boardWidth: number;
    boardHeight: number;
    boardPadding: number;
    ballDiameter: number;
    paddleWidth: number;
    paddleHeight: number;
    maxBounceAngle: number;
    playerSpeed: number;
    ballSpeed: number;
    ballSpeedEnvStep: number;
    ballSpeedEnvFinal: number;
    maxMutation: number;
    maxMutationEnvStep: number;
    maxMutationEnvFinal: number;
    wallMinAngle: number;
    wallMinAngleEnvStep: number;
    wallMinAngleEnvFinal: number;
    move: number;
    moveEnvStep: number;
    moveEnvFinal: number;
    bounce: number;
    bounceEnvStep: number;
    bounceEnvFinal: number;
    fail: number;
    failEnvStep: number;
    failEnvFinal: number;
    population: number;
    divisionThreshold: number;
    divisionScore: number;
    maxThreshold: number;
    maxBias: number;
    populationIncreaseMulti: number;
};
type Updater = 'ui' | 'env';
export declare function setConfig(values: Partial<Config>, updater?: Updater): void;
export declare function setConfig(fn: (prevValues: Config) => Partial<Config>, updater?: Updater): void;
type Callback = (config: Config, updater: Updater) => void;
export declare const subscribe: (callback: Callback) => () => void;
export {};
