declare let config: {
    KEYBOARD_REPEAT_TIMEOUT: number;
    boardWidth: number;
    boardHeight: number;
    boardPadding: number;
    ballDiameter: number;
    paddleWidth: number;
    paddleHeight: number;
    maxBounceAngle: number;
    playerSpeed: number;
    ballSpeed: number;
    population: number;
    moveStimulation: number;
    bounceStimulation: number;
    failStimulation: number;
    maxMutation: number;
    maxThreshold: number;
    maxBias: number;
};
export declare const getConfig: () => {
    KEYBOARD_REPEAT_TIMEOUT: number;
    boardWidth: number;
    boardHeight: number;
    boardPadding: number;
    ballDiameter: number;
    paddleWidth: number;
    paddleHeight: number;
    maxBounceAngle: number;
    playerSpeed: number;
    ballSpeed: number;
    population: number;
    moveStimulation: number;
    bounceStimulation: number;
    failStimulation: number;
    maxMutation: number;
    maxThreshold: number;
    maxBias: number;
};
export declare const setConfig: (values: Partial<typeof config>) => void;
export {};
