export { PlayerClass, Side, Controller, controllers } from './PlayerClass'
export { BallClass } from './BallClass'
export { EngineClass, FIRST_GENERATION_MULTI } from './EngineClass'
export { Intelligence, Weights, Layer } from './Intelligence'
export { GameSet } from './GameSet'
export { getConfig, setConfig, subscribe, Config } from './config'
